"""add personnel advance settlements

Revision ID: 4a02abf54669
Revises: c0dac6c6177d
Create Date: 2026-09-07 00:38:34.761013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a02abf54669'
down_revision = 'c0dac6c6177d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel_advance_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_type', sa.String(length=30), nullable=False),
    sa.Column('finance_account_id', sa.Integer(), nullable=False),
    sa.Column('cash_movement_id', sa.Integer(), nullable=True),
    sa.Column('expense_movement_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("settlement_type IN ('cash_return','expense_offset')", name='ck_personnel_settlement_type'),
    sa.CheckConstraint('amount > 0', name='ck_personnel_settlement_positive'),
    sa.ForeignKeyConstraint(['cash_movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['finance_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['personnel_finance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_movement_id'),
    sa.UniqueConstraint('expense_movement_id')
    )
    with op.batch_alter_table('personnel_advance_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personnel_advance_settlements_record_id'), ['record_id'], unique=False)

    with op.batch_alter_table('personnel_finance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnel_finance_records', schema=None) as batch_op:
        batch_op.drop_column('remaining_amount')

    with op.batch_alter_table('personnel_advance_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personnel_advance_settlements_record_id'))

    op.drop_table('personnel_advance_settlements')
    # ### end Alembic commands ###
