"""add finance and accounting module

Revision ID: 9f92a2f6ad18
Revises: c6d7e8f9a0b1
Create Date: 2026-09-06 23:58:43.679518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f92a2f6ad18'
down_revision = 'c6d7e8f9a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('account_category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('tax_no', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_category IN ('customer','supplier')", name='ck_current_account_category'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_current_account_site_code')
    )
    with op.batch_alter_table('current_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_accounts_account_category'), ['account_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_accounts_site_id'), ['site_id'], unique=False)

    op.create_table('finance_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('default_is_overhead', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('in','out','both')", name='ck_finance_category_direction'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_finance_category_site_code')
    )
    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_categories_site_id'), ['site_id'], unique=False)

    op.create_table('current_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_account_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entry_type IN ('receivable','payable')", name='ck_current_entry_type'),
    sa.CheckConstraint('amount > 0', name='ck_current_entry_amount_positive'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_current_entry_remaining_nonnegative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_account_id'], ['current_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_entries_current_account_id'), ['current_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_entries_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_entries_store_id'), ['store_id'], unique=False)

    op.create_table('finance_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('display_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_type IN ('cash','bank','pos_receivable')", name='ck_finance_account_type'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'code', name='uq_finance_account_scope_code'),
    sa.UniqueConstraint('site_id', 'store_id', 'display_code', name='uq_finance_account_scope_display_code')
    )
    with op.batch_alter_table('finance_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_accounts_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_accounts_store_id'), ['store_id'], unique=False)

    op.create_table('finance_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('activated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', name='uq_finance_activation_scope')
    )
    with op.batch_alter_table('finance_activations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_activations_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_activations_store_id'), ['store_id'], unique=False)

    op.create_table('monthly_overhead_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('budget_month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_monthly_overhead_nonnegative'),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'budget_month', 'category_id', name='uq_monthly_overhead_scope')
    )
    with op.batch_alter_table('monthly_overhead_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_overhead_budgets_budget_month'), ['budget_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_overhead_budgets_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_overhead_budgets_store_id'), ['store_id'], unique=False)

    op.create_table('obligation_recurrence_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_overhead', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("recurrence IN ('weekly','monthly')", name='ck_obligation_recurrence_plan_type'),
    sa.CheckConstraint("status IN ('active','stopped','completed')", name='ck_obligation_recurrence_plan_status'),
    sa.CheckConstraint('amount > 0', name='ck_obligation_recurrence_plan_positive'),
    sa.CheckConstraint('anchor_day >= 1 AND anchor_day <= 31', name='ck_obligation_recurrence_plan_anchor_day'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= first_due_date', name='ck_obligation_recurrence_plan_end_date'),
    sa.CheckConstraint('next_sequence >= 2', name='ck_obligation_recurrence_plan_next_sequence'),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_account_id'], ['current_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligation_recurrence_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_recurrence_plans_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_recurrence_plans_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_recurrence_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_recurrence_plans_store_id'), ['store_id'], unique=False)

    op.create_table('finance_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('is_overhead', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=180), nullable=False),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.Column('pair_key', sa.String(length=80), nullable=True),
    sa.Column('current_account_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("direction IN ('in','out')", name='ck_finance_movement_direction'),
    sa.CheckConstraint('amount > 0', name='ck_finance_movement_positive_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_account_id'], ['current_accounts.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'source_key', name='uq_finance_movement_source_key')
    )
    with op.batch_alter_table('finance_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_movements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_current_account_id'), ['current_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_is_overhead'), ['is_overhead'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_pair_key'), ['pair_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_reversal_of_id'), ['reversal_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_movements_store_id'), ['store_id'], unique=False)

    op.create_table('finance_payment_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'payment_method', name='uq_finance_payment_mapping')
    )
    with op.batch_alter_table('finance_payment_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_payment_mappings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_payment_mappings_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_payment_mappings_store_id'), ['store_id'], unique=False)

    op.create_table('finance_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('pair_key', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_transfer_positive_amount'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['finance_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_key')
    )
    with op.batch_alter_table('finance_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_transfers_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_transfers_store_id'), ['store_id'], unique=False)

    op.create_table('pos_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('pos_account_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('pair_key', sa.String(length=80), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('commission_amount >= 0', name='ck_pos_reconciliation_commission_nonnegative'),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate < 100', name='ck_pos_reconciliation_rate_range'),
    sa.CheckConstraint('gross_amount > 0', name='ck_pos_reconciliation_gross_positive'),
    sa.CheckConstraint('net_amount > 0', name='ck_pos_reconciliation_net_positive'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pos_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_key')
    )
    with op.batch_alter_table('pos_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_reconciliations_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_reconciliations_store_id'), ['store_id'], unique=False)

    op.create_table('short_term_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('recurrence_plan_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_sequence', sa.Integer(), nullable=True),
    sa.Column('is_overhead', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(recurrence_plan_id IS NULL AND recurrence_sequence IS NULL) OR (recurrence_plan_id IS NOT NULL AND recurrence_sequence > 0)', name='ck_short_obligation_plan_sequence'),
    sa.CheckConstraint('amount > 0', name='ck_short_obligation_positive'),
    sa.CheckConstraint('recurrence_plan_id IS NULL OR due_date IS NOT NULL', name='ck_short_obligation_plan_due_date'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_short_obligation_remaining'),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_account_id'], ['current_accounts.id'], ),
    sa.ForeignKeyConstraint(['recurrence_plan_id'], ['obligation_recurrence_plans.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurrence_plan_id', 'due_date', name='uq_short_obligation_plan_due_date')
    )
    with op.batch_alter_table('short_term_obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_term_obligations_recurrence_plan_id'), ['recurrence_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_term_obligations_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_term_obligations_store_id'), ['store_id'], unique=False)

    op.create_table('current_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_entry_id', sa.Integer(), nullable=False),
    sa.Column('finance_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_current_settlement_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_entry_id'], ['current_entries.id'], ),
    sa.ForeignKeyConstraint(['finance_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id')
    )
    with op.batch_alter_table('current_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_settlements_current_entry_id'), ['current_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_settlements_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_settlements_store_id'), ['store_id'], unique=False)

    op.create_table('finance_source_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_movement_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'source_type', 'source_id', name='uq_finance_source_state')
    )
    with op.batch_alter_table('finance_source_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_source_states_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_source_states_store_id'), ['store_id'], unique=False)

    op.create_table('obligation_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('finance_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_obligation_payment_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['short_term_obligations.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id')
    )
    with op.batch_alter_table('obligation_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligation_payments_obligation_id'), ['obligation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_payments_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligation_payments_store_id'), ['store_id'], unique=False)

    connection = op.get_bind()
    connection.execute(
        sa.text(
            "INSERT INTO features (code, name, sort_order) "
            "SELECT :code, :name, :sort_order "
            "WHERE NOT EXISTS (SELECT 1 FROM features WHERE code = :code)"
        ),
        {"code": "finance_management", "name": "Finans Yönetimi ve Ön Muhasebe", "sort_order": 140},
    )
    feature_id = connection.execute(
        sa.text("SELECT id FROM features WHERE code = 'finance_management'")
    ).scalar_one()
    permission_rows = (
        ("finance.access", "Finans Yönetimini görüntüle", "menu", None, 150),
        ("finance.ledger.view", "Kasa defterini görüntüle", "action", "finance.access", 151),
        ("finance.accounts.view", "Finans hesaplarını görüntüle", "action", "finance.access", 152),
        ("finance.accounts.manage", "Finans hesaplarını yönet", "action", "finance.access", 153),
        ("finance.manual.create", "Manuel finans hareketi oluştur", "action", "finance.access", 154),
        ("finance.transfer.create", "Hesap transferi oluştur", "action", "finance.access", 155),
        ("finance.pos_reconcile.create", "POS mutabakatı oluştur", "action", "finance.access", 156),
        ("finance.current.view", "Cari hesapları görüntüle", "action", "finance.access", 157),
        ("finance.current.manage", "Cari hesapları yönet", "action", "finance.access", 158),
        ("finance.overhead.view", "Genel gider bütçesini görüntüle", "action", "finance.access", 159),
        ("finance.overhead.manage", "Genel gider bütçesini yönet", "action", "finance.access", 160),
        ("finance.obligation.view", "Kısa vadeli borçları görüntüle", "action", "finance.access", 161),
        ("finance.obligation.manage", "Kısa vadeli borçları yönet", "action", "finance.access", 162),
    )
    permission_ids = {}
    for code, name, kind, parent_code, sort_order in permission_rows:
        parent_id = permission_ids.get(parent_code)
        connection.execute(
            sa.text(
                "INSERT INTO permissions (parent_id, feature_id, code, name, kind, sort_order) "
                "SELECT :parent_id, :feature_id, :code, :name, :kind, :sort_order "
                "WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = :code)"
            ),
            {
                "parent_id": parent_id,
                "feature_id": feature_id,
                "code": code,
                "name": name,
                "kind": kind,
                "sort_order": sort_order,
            },
        )
        permission_ids[code] = connection.execute(
            sa.text("SELECT id FROM permissions WHERE code = :code"), {"code": code}
        ).scalar_one()

    connection.execute(
        sa.text(
            "INSERT INTO package_features (package_id, feature_id) "
            "SELECT packages.id, :feature_id FROM packages "
            "WHERE packages.code = 'PRO' AND NOT EXISTS ("
            "SELECT 1 FROM package_features pf WHERE pf.package_id = packages.id AND pf.feature_id = :feature_id)"
        ),
        {"feature_id": feature_id},
    )
    for permission_id in permission_ids.values():
        connection.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) "
                "SELECT roles.id, :permission_id FROM roles "
                "WHERE roles.code = 'OWNER_MANAGER' AND NOT EXISTS ("
                "SELECT 1 FROM role_permissions rp WHERE rp.role_id = roles.id AND rp.permission_id = :permission_id)"
            ),
            {"permission_id": permission_id},
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    finance_permission_ids = connection.execute(
        sa.text("SELECT id FROM permissions WHERE code LIKE 'finance.%'")
    ).scalars().all()
    if finance_permission_ids:
        connection.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_id IN :ids").bindparams(
                sa.bindparam("ids", expanding=True)
            ),
            {"ids": tuple(finance_permission_ids)},
        )
    feature_id = connection.execute(
        sa.text("SELECT id FROM features WHERE code = 'finance_management'")
    ).scalar_one_or_none()
    if feature_id is not None:
        connection.execute(
            sa.text("DELETE FROM package_features WHERE feature_id = :feature_id"),
            {"feature_id": feature_id},
        )
    connection.execute(sa.text("DELETE FROM permissions WHERE code LIKE 'finance.%'"))
    connection.execute(sa.text("DELETE FROM features WHERE code = 'finance_management'"))

    with op.batch_alter_table('obligation_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligation_payments_store_id'))
        batch_op.drop_index(batch_op.f('ix_obligation_payments_site_id'))
        batch_op.drop_index(batch_op.f('ix_obligation_payments_obligation_id'))

    op.drop_table('obligation_payments')
    with op.batch_alter_table('finance_source_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_source_states_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_source_states_site_id'))

    op.drop_table('finance_source_states')
    with op.batch_alter_table('current_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_settlements_store_id'))
        batch_op.drop_index(batch_op.f('ix_current_settlements_site_id'))
        batch_op.drop_index(batch_op.f('ix_current_settlements_current_entry_id'))

    op.drop_table('current_settlements')
    with op.batch_alter_table('short_term_obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_term_obligations_store_id'))
        batch_op.drop_index(batch_op.f('ix_short_term_obligations_site_id'))
        batch_op.drop_index(batch_op.f('ix_short_term_obligations_recurrence_plan_id'))

    op.drop_table('short_term_obligations')
    with op.batch_alter_table('pos_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_reconciliations_store_id'))
        batch_op.drop_index(batch_op.f('ix_pos_reconciliations_site_id'))

    op.drop_table('pos_reconciliations')
    with op.batch_alter_table('finance_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_transfers_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_transfers_site_id'))

    op.drop_table('finance_transfers')
    with op.batch_alter_table('finance_payment_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_payment_mappings_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_payment_mappings_site_id'))
        batch_op.drop_index(batch_op.f('ix_finance_payment_mappings_account_id'))

    op.drop_table('finance_payment_mappings')
    with op.batch_alter_table('finance_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_movements_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_source_type'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_source_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_site_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_reversal_of_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_pair_key'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_is_overhead'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_current_account_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_category_id'))
        batch_op.drop_index(batch_op.f('ix_finance_movements_account_id'))

    op.drop_table('finance_movements')
    with op.batch_alter_table('obligation_recurrence_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligation_recurrence_plans_store_id'))
        batch_op.drop_index(batch_op.f('ix_obligation_recurrence_plans_status'))
        batch_op.drop_index(batch_op.f('ix_obligation_recurrence_plans_site_id'))
        batch_op.drop_index(batch_op.f('ix_obligation_recurrence_plans_next_due_date'))

    op.drop_table('obligation_recurrence_plans')
    with op.batch_alter_table('monthly_overhead_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_overhead_budgets_store_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_overhead_budgets_site_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_overhead_budgets_budget_month'))

    op.drop_table('monthly_overhead_budgets')
    with op.batch_alter_table('finance_activations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_activations_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_activations_site_id'))

    op.drop_table('finance_activations')
    with op.batch_alter_table('finance_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_accounts_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_accounts_site_id'))

    op.drop_table('finance_accounts')
    with op.batch_alter_table('current_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_entries_store_id'))
        batch_op.drop_index(batch_op.f('ix_current_entries_site_id'))
        batch_op.drop_index(batch_op.f('ix_current_entries_current_account_id'))

    op.drop_table('current_entries')
    with op.batch_alter_table('finance_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_categories_site_id'))

    op.drop_table('finance_categories')
    with op.batch_alter_table('current_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_accounts_site_id'))
        batch_op.drop_index(batch_op.f('ix_current_accounts_account_category'))

    op.drop_table('current_accounts')
    # ### end Alembic commands ###
