"""add staff friendly accounting workflows

Revision ID: c0dac6c6177d
Revises: 9f92a2f6ad18
Create Date: 2026-09-07 00:33:07.102464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dac6c6177d'
down_revision = '9f92a2f6ad18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cash_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_card', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counted_card', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('card_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_transfer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counted_transfer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transfer_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('handover_from', sa.String(length=140), nullable=False),
    sa.Column('handover_to', sa.String(length=140), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'store_id', 'business_date', name='uq_daily_closing_scope_date')
    )
    with op.batch_alter_table('daily_cash_closings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_cash_closings_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_cash_closings_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_cash_closings_store_id'), ['store_id'], unique=False)

    op.create_table('finance_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_finance_approval_status'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_finance_approval_entity')
    )
    with op.batch_alter_table('finance_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_approvals_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_approvals_store_id'), ['store_id'], unique=False)

    op.create_table('supplier_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_entry_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime', sa.String(length=120), nullable=True),
    sa.Column('attachment_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('gross_amount > 0', name='ck_supplier_invoice_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_entry_id'], ['current_entries.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['current_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_entry_id'),
    sa.UniqueConstraint('site_id', 'invoice_no', name='uq_supplier_invoice_site_no')
    )
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('expense_vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=180), nullable=True),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime', sa.String(length=120), nullable=True),
    sa.Column('attachment_data', sa.LargeBinary(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_expense_voucher_status'),
    sa.CheckConstraint('gross_amount > 0', name='ck_expense_voucher_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id')
    )
    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_vouchers_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_store_id'), ['store_id'], unique=False)

    op.create_table('personnel_finance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('personnel_name', sa.String(length=160), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime', sa.String(length=120), nullable=True),
    sa.Column('attachment_data', sa.LargeBinary(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("record_type IN ('advance','store_expense')", name='ck_personnel_finance_type'),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_personnel_finance_status'),
    sa.CheckConstraint('amount > 0', name='ck_personnel_finance_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['finance_movements.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id')
    )
    with op.batch_alter_table('personnel_finance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personnel_finance_records_personnel_name'), ['personnel_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_finance_records_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_finance_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_finance_records_store_id'), ['store_id'], unique=False)

    op.create_table('supplier_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_supplier_invoice_line_quantity'),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_lines_invoice_id'))

    op.drop_table('supplier_invoice_lines')
    with op.batch_alter_table('personnel_finance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personnel_finance_records_store_id'))
        batch_op.drop_index(batch_op.f('ix_personnel_finance_records_status'))
        batch_op.drop_index(batch_op.f('ix_personnel_finance_records_site_id'))
        batch_op.drop_index(batch_op.f('ix_personnel_finance_records_personnel_name'))

    op.drop_table('personnel_finance_records')
    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_store_id'))
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_status'))
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_site_id'))
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_expense_date'))

    op.drop_table('expense_vouchers')
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_store_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_site_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_due_date'))

    op.drop_table('supplier_invoices')
    with op.batch_alter_table('finance_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_approvals_store_id'))
        batch_op.drop_index(batch_op.f('ix_finance_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_finance_approvals_site_id'))

    op.drop_table('finance_approvals')
    with op.batch_alter_table('daily_cash_closings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_cash_closings_store_id'))
        batch_op.drop_index(batch_op.f('ix_daily_cash_closings_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_cash_closings_business_date'))

    op.drop_table('daily_cash_closings')
    # ### end Alembic commands ###
